name: test actions
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 1 * * *"  # run at every 1AM
jobs:
  test-sorting:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: |
          ls ${{ github.workspace }}
      - run: sorting/bubble_sort.py

  
